# Generated by Django 2.2.19 on 2022-06-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
